version: '3.8'
services:
  api:
    container_name: financialreportingqnaapi
    image: ${REGISTRY}/financialreportingqnaapi:${TAG}
    build: 
      context: src/api
      dockerfile: Dockerfile
  chat:
    container_name: financialreportingqnachat
    image: ${REGISTRY}/financialreportingqnachat:${TAG}
    build: 
      context: src/chat
      dockerfile: Dockerfile
  integration:
    container_name: financialreportingqnaintegration
    image: ${REGISTRY}/financialreportingqnaintegration:${TAG}
    build:
      context: src/integration
      dockerfile: Dockerfile