version: '3.8'
services:
  api:
    container_name: financialreportingqnaapi
    image: financialreportingqnaapi:${TAG}
    build: 
      context: src/api
      dockerfile: Dockerfile
  chat:
    container_name: financialreportingqnachat
    image: financialreportingqnachat:${TAG}
    build: 
      context: src/chat
      dockerfile: Dockerfile