version: '3.8'
services:
  api:
    image: ${REGISTRYNAME}/financialreportingqnaapi:${TAG}
    build: 
      context: src/api
      dockerfile: Dockerfile
  chat:
    image: ${REGISTRYNAME}/financialreportingqnachat:${TAG}
    build: 
      context: src/chat
      dockerfile: Dockerfile