version: '3.8'
services:
  api:
    image: financialreportingqnaapi:${TAG}
    build: 
      context: src/api
      dockerfile: Dockerfile
    container_name: api
  chat:
    image: financialreportingqnachat:${TAG}
    build: 
      context: src/chat
      dockerfile: Dockerfile