version: '3.8'
services:
  api:
    container_name: financialreportingqnaapi
    image: ${REGISTRY}/financialreportingqnaapi:${TAG}
    build: 
      context: src/api
      dockerfile: Dockerfile
    ports: 
      - 8000:8000
    env_file:
      - .env
    environment:
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME}
      - AZURE_AI_SEARCH_ENDPOINT=${AZURE_AI_SEARCH_ENDPOINT}
      - AZURE_AI_SEARCH_KEY=${AZURE_AI_SEARCH_KEY}
      - AZURE_AI_SEARCH_INDEX_NAME=${AZURE_AI_SEARCH_INDEX_NAME}
      - AZURE_AI_EMBEDDING_DEPLOYMENT_NAME=${AZURE_AI_EMBEDDING_DEPLOYMENT_NAME}
      - AZURE_OPENAI_MODEL_VERSION=${AZURE_OPENAI_MODEL_VERSION}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - DEBUG=${DEBUG}
      - ENABLE_LANGCHAIN_PLAYGROUND=${ENABLE_LANGCHAIN_PLAYGROUND}
  chat:
    container_name: financialreportingqnachat
    image: ${REGISTRY}/financialreportingqnachat:${TAG}
    build: 
      context: src/chat
      dockerfile: Dockerfile
    ports: 
      - 8501:8501
    env_file:
      - .env
    environment:
      - QNA_API_ENDPOINT=http://financialreportingqnaapi:8000/financial-report/
  integration:
    container_name: financialreportingqnaintegration
    image: ${REGISTRY}/financialreportingqnaintegration:${TAG}
    build:
      context: src/integration
      dockerfile: Dockerfile
    ports: 
      - 9500:9500
    env_file:
      - .env
    environment:
      - COMPANY_NAME=${COMPANY_NAME}
      - COMPANY_EMAIL_ADDRESS=${COMPANY_EMAIL_ADDRESS}
      - AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT=${AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT}
      - AZURE_DOCUMENT_INTELLIGENCE_KEY=${AZURE_DOCUMENT_INTELLIGENCE_KEY}
      - AZURE_AI_SEARCH_ENDPOINT=${AZURE_AI_SEARCH_ENDPOINT}
      - AZURE_AI_SEARCH_KEY=${AZURE_AI_SEARCH_KEY}
      - AZURE_AI_SEARCH_INDEX_NAME=${AZURE_AI_SEARCH_INDEX_NAME}
      - AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT=${AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_DEPLOYMENT=${AZURE_OPENAI_DEPLOYMENT}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - AZURE_STORAGE_ACCOUNT_KEY=${AZURE_STORAGE_ACCOUNT_KEY}
      - AZURE_STORAGE_CONTAINER_NAME=${AZURE_STORAGE_CONTAINER_NAME}
      - AZURE_COSMOSDB_CONNECTIONSTRING=${AZURE_COSMOSDB_CONNECTIONSTRING}
      - AZURE_COSMOSDB_DATABASE_NAME=${AZURE_COSMOSDB_DATABASE_NAME}
      - AZURE_COSMOSDB_COLLECTION_NAME=${AZURE_COSMOSDB_COLLECTION_NAME}
      - DOWNLOAD_ROOT_PATH=${DOWNLOAD_ROOT_PATH}
      - TIMEZONE=${TIMEZONE}