version: '3.8'
services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:api-dev
  api-dev:
    env_file:
      - .env
    build:
      context: ../../api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    environment:
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME}
      - AZURE_AI_SEARCH_ENDPOINT=${AZURE_AI_SEARCH_ENDPOINT}
      - AZURE_AI_SEARCH_KEY=${AZURE_AI_SEARCH_KEY}
      - AZURE_AI_SEARCH_INDEX_NAME=${AZURE_AI_SEARCH_INDEX_NAME}
      - AZURE_AI_EMBEDDING_DEPLOYMENT_NAME=${AZURE_AI_EMBEDDING_DEPLOYMENT_NAME}
      - AZURE_OPENAI_MODEL_VERSION=${AZURE_OPENAI_MODEL_VERSION}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - DEBUG=${DEBUG}
      - ENABLE_LANGCHAIN_PLAYGROUND=${ENABLE_LANGCHAIN_PLAYGROUND}
      
